language: ruby

rvm:
  - 1.9.3

env: "RAILS_ENV='test'"

script: "bundle exec rspec spec"

before_script:
  - "cp config/database.yml.example config/database.yml"
  - "bundle exec rake db:create"
  - "bundle exec rake db:schema:load"

notifications:
  recipients:
    - rmanhaes@gmail.com

branches:
  only:
    - master
