language: ruby

rvm:
  - 1.9.3
  - 1.9.2

env: "RAILS_ENV='test'"

script: "bundle exec rspec spec"

before_script:
  - "cp config/database.yml.example config/database.yml"
  - "bundle exec rake db:create"
  - "bundle exec rake db:schema:load"

notifications:
  recipients:
    - rmanhaes@gmail.com
    - d.camata@gmail.com
    - ebfjunior@gmail.com
    - henrique.avulso@gmail.com
    - thawan.fidelis@gmail.com
    - annabell.brasil@gmail.com
    - aride.moulin@gmail.com
    - mariana_gualhano@hotmail.com
    - lukspmarques@gmail.com

branches:
  only:
    - master
